import functions

def __main__():
    ciphertext = 'BGRWSLNGJXXHTTQNRZAEWYPBHWALXDTLKOEJBRJPVUAGZXVKQDUUPNMMPGPPAQOWRHGKBOGGEOZKAPTUKTPLGUADVXXGWNFBHRIHPRPLTSUUHOKKZPENJGSWRVASVHEILVYQEQZHFUGHSIGZHLLONMNGRRXKCAAYBAKGDNSWFPUNVVGICTGNXSQNFEALZHPHCYVAAAGOQQDVLNTZYDILQSGUBRWGYICGCBXKCUITVBXWSGHSEEGGHEAAPAGOFIDPHAKVTZUXGZBIBTLLRNKQNTGVSQXLZSNZBSQVOITFUKXRHAPIAMPMWJVCTGNTXLVZAIZVECQQAXOFYBFOGZWISEHYZCUBTBRXEUPAPENRBIQUSINTATKHUVUEBTXALVOBRNOGMQIPVFVKEHOKUOUVYMMFUDPEGNXVLVZUEBXLSPGVVERRLIZKSTHNBXXRVHTKJOMLDPHTIRTKIFQYLIAMLEOQUMAEKGXVWMNIPOXRWEVTOAKEAHDLZFEUPRHFFWUFKXQWQIMIZVECLPNBHNZGSDNPMNPUNPGJHDEYKTVQGKPUZGGPDPNCATKLFBOVVIGUKMQIVCROXHEGEHATF'
    [m, freq] = functions.find_length(ciphertext)
    k = functions.find_key(ciphertext, freq, m)
    plaintext = functions.decrypt(ciphertext, k)
    #print(plaintext)
    toString(plaintext)
    return 0


def toString(self):
    n = len(self)
    newstring=''
    for i in range(n):
        newstring += self[i]
    print(newstring)

if __name__ == __main__():
    __main__()


